### ISSUE TITLE
Idler bearing too low?

### ISSUE THREAD

**Issue by mandrav** [AxMod3DPrint/Drakon-Extruder#1]
Hi,

the idler bearing looks to be too low wrt the filament path, at least 1-2mm. Is this a known issue?

**Comment by ViperWorx** [comment]
Hi, there's a lot of deviance with MK8 drive gears. This is dead on for the ones I have to hand as well as the E3D Hobbgoblin. 

If you're looking at the CAD, the MK8 model is way out and caused a fair few issues.

**Comment by mandrav** [comment]
That's what I figured...
Thankfully the files are in freecad format so I can have a play :)

This looks like a great DIY extruder, great job!

**Comment by ViperWorx** [comment]
Just a note on the FreeCAD file, I've tried to get them to a point where where you change something and nothing breaks, but if you're aware of the way FreeCAD works, this isn't always possible, so there may be some glitches,

**Comment by mandrav** [comment]
I know.
Yet, moving the idler bearing a bit upwards didn't break anything. Printing it now.

**Comment by mandrav** [comment]
I have to note that in the freecad file, the bearing is indeed on the low side (not centered on) of the filament path.

**Comment by ViperWorx** [comment]
I recently dropped the bearing due to it being too high, see commit f9bee95f08c6e41a0b883e2b43869f88878935cb. The path may not be exactly dead on, the bearing was changed from real world usage and not from CAD. 

I also have 4 printers running Drakons with a good amount of print time and tweaking having gone into them from real world use, over the CAD being totally exact.

**Comment by ViperWorx** [comment]
Just as a note I have reverted the 1mm drop of the idler bearing as the gear I was working with was way off. See commit 6c8159a9f6e23e9846f1c0cf4f509f1205279de6
